export const defaultCorpus = [
  // Thanks & Appreciation
  'thank you so much',
  'thanks for letting me know',
  'thanks for the help',
  'thanks for reaching out',
  'i appreciate it',
  'appreciate you',
  'appreciate the update',
  'much appreciated',

  // Quick Confirmations
  'sounds good',
  'sounds great',
  'sounds perfect',
  'makes sense',
  'got it',
  'will do',
  'on it',
  'for sure',
  'absolutely',
  'definitely',
  'of course',
  'sure thing',
  'no problem',
  'no worries',
  'all good',
  'perfect timing',
  'works for me',

  // Casual Conversation
  'how are you',
  'how are you doing',
  "how's it going",
  "what's up",
  'how have you been',
  'what are you up to',
  'what have you been up to',
  'long time no see',
  'good to hear from you',
  'great to see you',
  'nice to meet you',
  'pleasure to meet you',

  // Agreements & Reactions
  "you're right",
  'i agree',
  'i completely agree',
  'good point',
  'fair enough',
  "that's true",
  'that makes sense',
  'i see what you mean',
  'i understand',
  'i get it',
  'i hear you',
  "couldn't agree more",

  // Positivity & Encouragement
  "that's awesome",
  "that's amazing",
  "that's great",
  "that's fantastic",
  "that's perfect",
  'love it',
  'nice work',
  'great job',
  'well done',
  'keep it up',
  'you got this',
  'proud of you',
  'happy for you',
  'congrats',
  'congratulations',

  // Plans & Availability
  'let me know',
  'let me know what you think',
  "let me know when you're free",
  'let me know if that works',
  'are you free',
  'are you around',
  'are you available',
  'when works for you',
  'what time works',
  'does that work',
  "i'm free",
  "i'm available",
  "i'm around",
  "i'm down",
  "i'm in",
  'count me in',

  // Goodbyes & Closings
  'talk soon',
  'talk later',
  'see you later',
  'see you soon',
  'see you then',
  'see you tomorrow',
  'catch you later',
  'take care',
  'have a good one',
  'have a great day',
  'have a great weekend',
  'enjoy your day',
  'enjoy your weekend',

  // Responses & Updates
  'just wanted to let you know',
  'wanted to give you a heads up',
  'quick update',
  'just checking in',
  'following up on',
  'circling back on',
  'wanted to touch base',
  "i'll let you know",
  "i'll keep you posted",
  "i'll get back to you",
  "i'll take a look",
  "i'll check it out",
  "i'll figure it out",
  "i'll see what i can do",

  // Thinking & Consideration
  'let me think about it',
  'let me check',
  'give me a second',
  'give me a minute',
  'one second',
  'hold on',
  'not sure yet',
  'need to think about it',
  "i'll have to check",
  'let me get back to you on that',

  // Welcomes & Apologies
  "you're welcome",
  'happy to help',
  'glad i could help',
  'anytime',
  'my pleasure',
  'sorry about that',
  'sorry for the delay',
  'my bad',
  'my apologies',
  'apologies for',

  // Questions & Requests
  'can you send me',
  'can you share',
  'could you send',
  'would you mind',
  'do you have',
  'do you know',
  'did you get a chance to',
  'have you had a chance to',
  'when you get a chance',
  'whenever you get a chance',
  'no rush',

  // Work & Collaboration
  "i'm working on",
  "i'm looking into",
  'let me look into that',
  'let me check on that',
  "let's schedule a call",
  "let's hop on a call",
  "let's discuss",
  "let's sync up",
  "let's touch base",
  "i'll send over",
  "i'll share",
  'attached is',
  "here's what i'm thinking",
  'what do you think about',

  // Tech & Development
  'this should work',
  'let me test this',
  "i'll run the tests",
  "i'll deploy",
  'pushed to',
  'merged the pr',
  'looks good to me',
  'shipping this',
  'need to debug',
  'still investigating',
  'fixed the bug',
  'found the issue',

  // General Phrases
  'in the meantime',
  'by the way',
  'speaking of which',
  'on another note',
  'just a heads up',
  "for what it's worth",
  'at the end of the day',
  'to be honest',
  'to be fair',
  'that being said',
  'all things considered',
  'as mentioned',
  'as discussed',
  'for reference',
  'for context',

  // Casual Expressions
  'not gonna lie',
  'to be honest',
  'honestly',
  'literally',
  'basically',
  'pretty much',
  'kind of',
  'sort of',
  'i mean',
  'you know what i mean',
  'know what i mean',

  // Time References
  'right now',
  'at the moment',
  'as we speak',
  'just finished',
  'just started',
  'about to',
  'getting ready to',
  'in a bit',
  'in a few',
  'later today',
  'tomorrow morning',
  'next week',
  'see you at',

  // Social & Fun
  "can't wait",
  'excited for',
  'pumped for',
  'hyped for',
  'dying to',
  'looking forward to',
  'wish i could',
  'hope you can',
  'would love to',
  'down to',
  'up for',
  'totally down',
  "let's do it",
  "i'm game",

  // More Questions
  'what do you think',
  'what are your thoughts on',
  'any thoughts on',
  'have you seen',
  'have you heard about',
  'did you see',
  'did you hear',
  'have you tried',
  'ever been to',
  'you coming to',

  // Opinions & Feelings
  'i think',
  'i feel like',
  'seems like',
  'looks like',
  'feels like',
  "i'm thinking",
  'not sure if',
  'wondering if',
  'curious if',
  'hope that',
  'wish that',
];
